[project]
name = "mythril_theme"
version = "0.0.1"
description = "Mythril color theme for Frappe"
requires-python = ">=3.10"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "mythril_theme"
